### PR TITLE
Mark C functions as nothrow @nogc.

### LINKED ISSUE #36: Extern(C) functions should be `nothrow @nogc`
If they don't call D code internally, C functions should be marked `extern(C) nothrow @nogc { … }`.

### PR DESCRIPTION
**Pull request by rcorre**
Resolves #36: Extern(C) functions should be `nothrow @nogc`

### CODE REVIEW

**Comment by rcorre** [comment]
I swapped [an old game](https://github.com/rcorre/terra-arcana) over to the `nothrow @nogc` version and it worked alright.

**Comment by rcorre** [comment]
Also, whether or not you merge this it would be nice to have a new tag to pick up f59b20103004cc078470311de8de260261124369 and avoid deprecation warnings.

**Comment by SiegeLord** [comment]
Thanks, you're the best!

**Comment by rcorre** [comment]
Naw, you're the best :P

**Comment by mleise** [comment]
You're both quite good.

**Pull request merged**
