### PR TITLE
Provide early feedback on a bad environment in the example.

### LINKED ISSUE #30: segfault ubuntu + ldc2
I just downloaded a fresh LDC2, compiled it, and then tried both DAlleg and DAlleg unstable, and they both compile fine but segfault when running the example program.

Program received signal SIGSEGV, Segmentation fault.

al_create_display (w=500, h=500) at /home/[USER]/Downloads/allegro-5.1.11/src/display.c:47

47	   driver = system->vt->get_display_driver();

(gdb) bt
#0  al_create_display (w=500, h=500) at /home/[USER]/Downloads/allegro-5.1.11/src/display.c:47
#1  0x0000000000402c3a in a5test.main() ()
#2  0x0000000000425c1e in allegro5.system.al_run_allegro() ()
#3  0x0000000000425bf4 in allegro5.system.al_run_allegro() ()
#4  0x0000000000402bee in D main ()
#5  0x0000000000414814 in _d_run_main ()
#6  0x0000000000409a98 in main ()

---> It appears that al_init() is returning 0 and the example program does not check for this condition. Of course, why it's failing on my system is huge question.

I have a 5.1.11 Allegro 5 program compiling and running just fine on my system. (Just checked again to be sure.) 

[edit] I added a version writefln statement. It reports 5.1.11.1. Which is the exact same version I'm compiling my C++ one in.

[edit] Okay, I'm stepping through with gdb and it looks like:

83888641 - version
83954433 - library version

But in my C++ program it reports:

83954433 
83954433

Strange indeed...

Perhaps DAlleg has slightly older Allegro headers?

### PR DESCRIPTION
**Pull request by rcorre**
Resolves #30

### CODE REVIEW

**Comment by SiegeLord** [comment]
Merged with slight modifications as 731140d. I had a slightly more informative fix in the pipeline. Thanks!

**Comment by rcorre** [comment]
Cool, that extra version check should be a big help -- I've hit that myself a few times.
Out of curiosity, do you know why the version string matters in al_init?
I was working on binding another library (chipmunk2d), and noticed that I could, for example, use my 7.0.1 bindings with 7.0.0. However, with Allegro, the version string check means you need an exact match, which can be annoying if the difference is in parts of the API you aren't using. Is this intentional?

**Comment by SiegeLord** [comment]
This is a peculiarity of the 5.1.x versions. 5.0.x and in the future 5.2.x versions will behave in the way you expect. 5.1.x is the unstable branch, so it's allowed to change arbitrarily even for patch version bumps.

**Comment by rcorre** [comment]
Interesting, thanks.

**Pull request closed without merging**
