### PR TITLE
Update bindings to 5.2.0.

### PR DESCRIPTION
**Pull request by rcorre**
Not sure if you want to create a new 5.2 branch -- just put the PR against 5.1 for now to show the diff.

Do we want to mirror those `ALLEGRO_UNSTABLE` conditional compilation flags? Or should we just create bindings for everyting regardless?

### CODE REVIEW

**Comment by SiegeLord** [comment]
I think I'd prefer this to replace the master branch. I do think it's a good idea to mimic the `ALLEGRO_UNSTABLE` flags. I think the way you've implemented it is missing a location where the '_SRC' versions are defined (I guess they'll be defined when you compile the libraries?).

**Comment by GassaFM** [comment]
>I think I'd prefer this to replace the master branch.

It may be worth to save the current master as branch 5.0 then.

**Comment by rcorre** [comment]
> I think the way you've implemented it is missing a location where the '_SRC' versions are defined

How do you mean? The `UNSTABLE` and `_SRC` versions would presumably be enabled by the `version=` switch when compiling. I'm not sure if that will propogate to sub-projects using dub though. We might have to add a dub configuration for it.

**Comment by rcorre** [comment]
Just confimed versions declared at a top-level dub project propogate to dependencies, so you should be able to say `versions "ALLEGRO_UNSTABLE"` in your `dub.sdl` and get the unstable features.

**Comment by SiegeLord** [comment]
Merged as 2e2669f6095ff35bfbdb23697c467674d4ca5bc2 into the master branch. I forked off the old master into the 5.0 branch as well. Thanks!

**Pull request closed without merging**
